### ISSUE TITLE
调用方式写错了

### ISSUE THREAD

**Issue by yi-ge** [yumemor/cordova-plugin-alipay#2]
调用方式写错了，应该是：window.plugins.Alipay.pay。此外，配置后一直报错支付失败，具体原因在查。

**Comment by akarineren** [comment]
好的，我检查下

**Comment by akarineren** [comment]
实在不好意思，npm上面没有同步过来，修改版本过后忘记更新README，现已修改 主要是调用方式变了 其它的话正常，不考虑aliipay更换支付方式，你的支付失败应该是key没有正确配置，如果后面实在没有解决，请new lssues
